services:
  follow-claim:
    container_name: follow-claim
    image: missuo/follow-claim:latest
    restart: unless-stopped
    environment:
      # Cookie (Support multiple cookies, separated by commas) (Required)
      - COOKIE=
      # Bark URL (Optional)
      - BARK_URL=
      # Use UTC Time (UTC 00:05 is 08:05 in China) (Optional, Default: 00:05)
      - SCHEDULED_TIME=00:05
      # Telegram Bot Token (Optional)
      - TELEGRAM_BOT_TOKEN=
      # Telegram Chat ID (Optional)
      - TELEGRAM_CHAT_ID=
